markdown: kramdown
highlighter: rouge
permalink: /posts/:title
auto: true

name: Devang Sampat
title: Day In Dev
url: http://dayindev.com
description: On not getting fired on Day 1  
github: DevangS 
gravatar_url: https://www.gravatar.com/avatar/6b5cba862133e5f3f5d5a2f8e37e8f32.png
